let sample = [
  {
    deleteAt: false,
    _id: "6165513adc423b001dd9c044",
    name: "Saigon Emerald Resort",
    guests: 2,
    bedRoom: 2,
    bath: 3,
    description: "Khách Sạn này thật tuyệt vời",
    price: 100000,
    elevator: false,
    hotTub: true,
    pool: true,
    indoorFireplace: false,
    dryer: true,
    gym: false,
    kitchen: true,
    wifi: true,
    heating: true,
    cableTV: true,
    locationId: {
      deleteAt: false,
      name: "Thành phố Đà Nẵng",
      province: "Đà Nẵng",
      country: "Việt Nam",
      valueate: 8,
      image:
        "https://airbnb.cybersoft.edu.vn/public/temp/1651290776928_shutterstock-1169930359-4299-1593590420.jpg",
    },
    __v: 0,
    image:
      "https://airbnb.cybersoft.edu.vn/public/images/room/1653067766301_764854.png",
  },
  {
    deleteAt: false,
    _id: "61655587dc423b001dd9c04a",
    name: "Khách Sạn Hồng Hào",
    guests: 2,
    bedRoom: 0,
    bath: 5,
    description: "Khách Sạn đẹp quá đi thôi",
    price: 20000000,
    elevator: true,
    hotTub: true,
    pool: true,
    indoorFireplace: true,
    dryer: true,
    gym: true,
    kitchen: true,
    wifi: true,
    heating: true,
    cableTV: false,
    __v: 0,
    image:
      "https://airbnb.cybersoft.edu.vn/public/images/room/1658417402740_hotel-room-design-trends-italianbark-interior-design-blog.jpg",
    locationId: {
      deleteAt: false,
      name: "Chùa Cầu Hội An",
      province: "Hội An",
      country: "Việt Nam",
      valueate: 10,
      image:
        "https://airbnb.cybersoft.edu.vn/public/temp/1656459879803_chua-cau-1.jpg",
    },
  },
  {
    deleteAt: false,
    _id: "616555d3dc423b001dd9c053",
    name: "Phòng Siêu Vip Pro",
    guests: 5,
    bedRoom: 2,
    bath: 3,
    description: "Khách Sạn này thật tuyệt vời",
    price: 100000,
    elevator: true,
    hotTub: true,
    pool: true,
    indoorFireplace: false,
    dryer: false,
    gym: false,
    kitchen: true,
    wifi: true,
    heating: true,
    cableTV: true,
    locationId: {
      deleteAt: false,
      name: "Khu phố tây Trần Phú",
      province: "Nha Trang, Khánh Hoà",
      country: "Việt Nam",
      valueate: 7,
      image:
        "https://airbnb.cybersoft.edu.vn/public/temp/1656432692952_5e984d8059d27.jpg",
    },
    __v: 0,
    image:
      "https://airbnb.cybersoft.edu.vn/public/images/room/1654708437172_dirtiest-1170x650.jpg",
  },
  {
    deleteAt: false,
    _id: "616596b9dc423b001dd9c06e",
    name: "Khách Sạn Palace",
    guests: 8,
    bedRoom: 5,
    bath: 5,
    description:
      "Khách sạn Palace là một khách sạn 4 sao đầu tiên của Vũng Tàu, tọa lạc ngay tại trung tâm thành phố, rất thuận tiện cho du khách đi thăm quan các điểm du lịch, giải trí, mua sắm. Đặc biệt Khách sạn Palace tự hào là sự lựa chọn tin cậy để tổ chức các sự kiện quan trọng của Tỉnh, các hội nghị quốc tế, là nơi tiếp đón các đoàn khách ngoại giao, và các nguyên thủ quốc gia Khách sạn Palace Vũng tàu bao gồm 95 phòng ngủ và 17 căn hộ cao cấp đầy đủ tiện nghi, là trung tâm hội nghị quốc tế và hiện đại nhất tại Vũng Tàu, khu vực nhà hàng và phòng tiệc có khả năng phục vụ cùng lúc lên tới 1.000 khách.  Câu lạc bộ Palace Gamming & Bar nằm trong khuôn viên khách sạn cung cấp dịch vụ trò chơi có thưởng cho các du khách là người nước ngoài và Việt kiều. Với hệ thống máy được trang bị hiện đại tạo cho khách hàng sẽ có cảm giác thư giãn và thích thú  Tại khách sạn Palace với hệ thống dịch vụ hoàn chỉnh, phong cách phục vụ chuyên nghiệp cùng sự thân thiện của đội ngũ nhân viên khách sạn, chúng tôi cam kết sẽ đem đến sự hài lòng cho Quý Khách",
    price: 690000,
    elevator: true,
    hotTub: true,
    pool: true,
    indoorFireplace: false,
    dryer: false,
    gym: false,
    kitchen: true,
    wifi: true,
    heating: true,
    cableTV: true,
    __v: 0,
    image:
      "https://airbnb.cybersoft.edu.vn/public/images/room/1658417426651_dirtiest-1170x650.jpg",
    locationId: {
      deleteAt: false,
      name: "Chùa Cầu Hội An",
      province: "Hội An",
      country: "Việt Nam",
      valueate: 10,
      image:
        "https://airbnb.cybersoft.edu.vn/public/temp/1656459879803_chua-cau-1.jpg",
    },
  },
  {
    deleteAt: false,
    _id: "6166562edc423b001dd9c0cf",
    name: "Khách Sạn Cap Saint Jacques",
    guests: 2,
    bedRoom: 2,
    bath: 3,
    description:
      " Khách sạn Cap Saint Jacques là khách sạn bốn sao nổi tiếng tại Vũng Tàu, nằm ở vị trí đẹp ở Bãi Sau, chỉ cách 200 mét từ sân golf Paradise và năm phút từ trung tâm thành phố Vũng Tàu, rất thuận tiện đi đến các địa điểm chính. Khách sạn có các loại phòng sang trọng và đầy đủ tiện nghi đạt chuẩn bốn sao như két an tòan, truyền hình vệ tinh, Internet WIFI. Đối với khách là doanh nhân thì có phòng hội nghị với thiết bị như máy chiếu, hệ thống loa và màn hình. Nhà hàng của khách sạn phục vụ các món ăn Việt Nam phong phú chế biến từ hải sản. Ngòai ra, những du khách tìm kiếm sự thư giãn qua vận động thể thao có thể sử dụng các tiện ích như sân tennis, hồ bơi và phòng tập thể dục. Khách sạn Cap Saint Jacques đúng là sự lựa chọn phù hợp cho những du khách đang tìm kiếm một nơi yên tĩnh vào cuối ngày. ",
    price: 1050000,
    elevator: true,
    hotTub: true,
    pool: true,
    indoorFireplace: false,
    dryer: true,
    gym: false,
    kitchen: false,
    wifi: true,
    heating: true,
    cableTV: true,
    __v: 0,
    image:
      "https://airbnb.cybersoft.edu.vn/public/images/room/1657798248527_images.jpg",
    locationId: {
      deleteAt: false,
      name: "Khu du lịch Suối Mơ",
      province: "Vũng Tàu",
      country: "Việt Nam",
      valueate: 9,
      image:
        "https://airbnb.cybersoft.edu.vn/public/temp/1656528784835_suoi-mo-park1.jpg",
    },
  },
];
